### PR TITLE
ACMAPP-86: updating jar file and updating errored files (#87)

### PR DESCRIPTION
**Pull request by kwinborne**

### CODE REVIEW

**Comment by sambutler1017** [comment]
What is this PR?

**Comment by kwinborne** [comment]
We need to pull the library into the epic branch.

**Comment by sambutler1017** [comment]
It says you have conflicts. Can you fix those before we merge?

**Comment by kwinborne** [comment]
Working on that now. I had to pull in the development branch again and I need to pull the epic branch in next.

**Comment by kwinborne** [comment]
Well it would help if I weren't pulling from my fork.

**Pull request closed without merging**
